spring:
  application:
    name: Lab2
  datasource:
<<<<<<<< HEAD:Assignment/target/classes/application.yml
    url: jdbc:mysql://172.17.18.6:3306/waaAssigDB?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    password: ${DB_PASSWORD}
    username: ${DB_USER}
  #    url: jdbc:mysql://localhost:3306/waa_assignmentDB?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
========
#    password: ${DB_PASSWORD}
#    username: ${DB_USER}
    url: jdbc:mysql://172.17.18.6:3306/waaAssigDB
    username: reconov
    password: reconov
#    url: jdbc:mysql://localhost:3306/waa_assignmentDB?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
#    username: 'root'
#    password: 'password'
>>>>>>>> Lab8:Assignment/project_config/application.yml
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
    show-sql: true
    defer-datasource-initialization: true
    generate-ddl: true
  sql:
    init:
      mode: always
  main:
<<<<<<<< HEAD:Assignment/target/classes/application.yml
    banner-mode: "console"
    allow-circular-references: true

========
    banner-mode: "off"
>>>>>>>> Lab8:Assignment/project_config/application.yml
server:
  port: 4000

jwt:
  secret: 'someReallyComplicatedStringFromFileSomewhere'

#logging:
#  pattern:
#    console:
<<<<<<<< HEAD:Assignment/target/classes/application.yml

========
>>>>>>>> Lab8:Assignment/project_config/application.yml
