spring:
  application:
    name: Lab2
  datasource:
    password: password
    url: jdbc:mysql://localhost:3306/waa_assignmentDB
    username: root
#    driver-class-name: com.mysql
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
    show-sql: true
    defer-datasource-initialization: true
    generate-ddl: true
  sql:
    init:
      mode: always
server:
  port: 4000
