spring:
  application:
    name: Lab2
  datasource:
    password: password
#    url: jdbc:mysql://localhost:3306/waa_assignmentDB
    url: jdbc:mysql://172.17.18.6:3306/waaAssigDB
    username: root
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
    show-sql: true
    defer-datasource-initialization: true
    generate-ddl: true
  sql:
    init:
      mode: always
server:
  port: 4000

jwt:
  secret: 'someReallyComplicatedStringFromFileSomewhere'
