spring:
  application:
    name: Lab2
  datasource:
    url: {database-connection-string}
  jpa:
    hibernate:
      ddl-auto: update
#      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
    show-sql: true
    defer-datasource-initialization: true
    generate-ddl: true
  sql:
    init:
      mode: always
server:
  port: 4000
