spring:
  application:
    name: Lab2
  datasource:
     password: ${DB_PASSWORD}
#    url: jdbc:mysql://localhost:3306/waa_assignmentDB
    username: ${DB_USER}
    url: {database-connection-string}
  jpa:
    hibernate:
      ddl-auto: update
#      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
    show-sql: true
    defer-datasource-initialization: true
    generate-ddl: true
  sql:
    init:
      mode: always
server:
  port: 4000

jwt:
  secret: 'someReallyComplicatedStringFromFileSomewhere'
